### PR TITLE
Automate installation of dependencies in notebook.

### PR DESCRIPTION
**Pull request by ubergarm**
I added a couple things that may help folks get the dependencies installed for this:

1. A `start-jupyter.sh` script if you want to keep it all in a docker container (supports GPUs).
1. Some cells at the top of `inference_tts.ipynb` to help install dependencies.

Also a few minor tweaks thanks to [u/SignalCompetitive582](https://www.reddit.com/r/LocalLLaMA/comments/1bqmuto/comment/kx3ijqf/?utm_source=reddit&utm_medium=web2x&context=3) to get it running.

No pressure to merge this, but leaving it here for folks who are unable to get over the dependencies hump. Maybe it will help someone.

Cheers!

### CODE REVIEW

**Comment by jasonppy** [comment]
Thanks! This is super helpful!

I'll have a try and merge it today or tomorrow

**Comment by ubergarm** [comment]
One last snafu I see, it seems that the `mfa` cli will re-use previous runs if you run it again. So it won't generate a valid output in `temp/mfa_alignments/` if you already ran it once on the demo.

Add `--clean` to force it to actually use the new file. Not an obvious failure case for someone who will likely run the demo, then try to add their own .wav file.

example:
```
# current code:
mfa align -j 1 --output_format csv  ......
# suggested change:
mfa align --clean -j 1 --output_format csv  ......
```

Anyway, neither here nor there. Thanks much for any/all of your effort!

**Comment by jasonppy** [comment]
I just tried it out on a remote linux machine, for some reason after I install everything and reached STOP, I couldn't find the voicecraft kernel, there is only one default kernel
image

even if I restart the image

I can `conda activate voicecraft` inside `docker exec -it jupyter /bin/bash` though

might be an issue on my end.

**Comment by ubergarm** [comment]
Ahh thanks for trying it, your screen shot is the correct place. To be honest I never use conda. It could be two possible things:

1. I'm using a slightly older jupyter notebook, but should be fine.
2. I realize I ran another command once in my notebook right before the `STOP` cell. Could try adding this to the cell right above `STOP`, as it might be what actually tells jupyter about the new kernel:

```
!source ~/.bashrc && \
    conda activate voicecraft && \
    python3 -m ipykernel install --user --name=voicecraft
```

Check the end of the output will say something like:
```
Installed kernelspec voicecraft in /home/myusername/.local/share/jupyter/kernels/voicecraft
```

Finally, I had to refresh the browser before the new kernel shows up in the list.

Hopefully some combination of the above will fix it.

Its not perfect, but a step along the path to getting the dependencies managed and installable more easily hopefully.

Thanks again for your all your time!

**Comment by jay-c88** [comment]
Thanks for this. Works on my windows machine.

Quickstart works on Windows too even without wsl, Just need docker installed, no need to install nvidia toolkit on Windows if you have Nvidia driver anyway.

Converted your script to batch file to run without wsl.

start-jupyter.bat

```
@echo off

docker start jupyter > nul 2> nul || ^
docker run -it ^
-d ^
--gpus all ^
-p 8888:8888 ^
--name jupyter ^
--user root ^
-e NB_USER="%username%" ^
-e CHOWN_HOME=yes ^
-e GRANT_SUDO=yes ^
-w "/home/%username%" ^
-v %cd%:"/home/%username%/work" ^
jupyter/base-notebook

pause
```

**Comment by ZeroHackz** [comment]
> Thanks for this. Works on my windows machine.
> 
> Quickstart works on Windows too even without wsl, Just need docker installed, no need to install nvidia toolkit on Windows if you have Nvidia driver anyway.
> 
> Converted your script to batch file to run without wsl.
> 
> start-jupyter.bat
> 
> ```
> @echo off
> 
> docker start jupyter > nul 2> nul || ^
> docker run -it ^
> -d ^
> --gpus all ^
> -p 8888:8888 ^
> --name jupyter ^
> --user root ^
> -e NB_USER="%username%" ^
> -e CHOWN_HOME=yes ^
> -e GRANT_SUDO=yes ^
> -w "/home/%username%" ^
> -v %cd%:"/home/%username%/work" ^
> jupyter/base-notebook
> 
> pause
> ```

how did you fix the espeak reference on windows? I've installed the released msi form the git repo, seem not to be recognized as installed.

**Comment by ubergarm** [comment]
@jay-c88 - nice job with the windows bat file! I'll add that to the PR and credit you in a comment.

@ZeroHackz you don't need to install it on the windows host machine, it is installed inside the docker linux context. use the bat file above and try that.

@jasonppy i'll add a commit to this to roll in the above findings and work here in a few minutes.

**Comment by ubergarm** [comment]
:oof: one second, i accidentally had some cruft in my notebook from my personal testing, will revert that and force push to my branch ASAP... lol sorry...

**Comment by jay-c88** [comment]
> how did you fix the espeak reference on windows? I've installed the released msi form the git repo, seem not to be recognized as installed.

There is nothing to do in Windows except to install docker and run the bat file, since all the code then runs inside docker. No issues at all via notebook in the docker since it's a ubuntu system. Just use `docker logs jupyter` when the docker is running to get the jupyter lab link.

**Pull request merged**
